# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/events?loc=Kielce
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/events
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/events/5
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/exhibitors
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/exhibitors/1
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/exhibitors?nam=com
Accept: application/json

###

POST http://127.0.0.1:8000/api/v1/auth/signup
Accept: application/json